package com.dluobida.bluecat.finance.core.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig expandDataDaoConfig;

    private final ExpandDataDao expandDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        expandDataDaoConfig = daoConfigMap.get(ExpandDataDao.class).clone();
        expandDataDaoConfig.initIdentityScope(type);

        expandDataDao = new ExpandDataDao(expandDataDaoConfig, this);

        registerDao(ExpandData.class, expandDataDao);
    }
    
    public void clear() {
        expandDataDaoConfig.clearIdentityScope();
    }

    public ExpandDataDao getExpandDataDao() {
        return expandDataDao;
    }

}
