package com.dluobida.bluecat.finance.core.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dluobida.bluecat.finance.core.db.table.AccountData;
import com.dluobida.bluecat.finance.core.db.table.ExpandData;

import com.dluobida.bluecat.finance.core.greendao.AccountDataDao;
import com.dluobida.bluecat.finance.core.greendao.ExpandDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDataDaoConfig;
    private final DaoConfig expandDataDaoConfig;

    private final AccountDataDao accountDataDao;
    private final ExpandDataDao expandDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDataDaoConfig = daoConfigMap.get(AccountDataDao.class).clone();
        accountDataDaoConfig.initIdentityScope(type);

        expandDataDaoConfig = daoConfigMap.get(ExpandDataDao.class).clone();
        expandDataDaoConfig.initIdentityScope(type);

        accountDataDao = new AccountDataDao(accountDataDaoConfig, this);
        expandDataDao = new ExpandDataDao(expandDataDaoConfig, this);

        registerDao(AccountData.class, accountDataDao);
        registerDao(ExpandData.class, expandDataDao);
    }
    
    public void clear() {
        accountDataDaoConfig.clearIdentityScope();
        expandDataDaoConfig.clearIdentityScope();
    }

    public AccountDataDao getAccountDataDao() {
        return accountDataDao;
    }

    public ExpandDataDao getExpandDataDao() {
        return expandDataDao;
    }

}
